language: cpp
sudo: false

addons:
  apt:
    sources:
    - george-edison55-precise-backports
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - gcc-5
    - libsqlite3-dev

compiler: g++-5
