language: cpp
sudo: false

addons:
  apt:
    sources:
    - george-edison55-precise-backports
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - gcc-5
    - libsqlite3-dev

before_install:
- export CC=/usr/bin/gcc-5
- export CXX=/usr/bin/g++-5