language: cpp
sudo: false

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - gcc-4.9
      - libsqlite3-dev

before_install:
  - export CXX="g++-4.9" CC="gcc-4.9"