language: cpp
sudo: false

env: GCC_VERSION=5 CPP=14
addons: &gcc5
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - gcc-5
      - libsqlite3-dev

before_install:
  - export CXX="g++-5" CC="gcc-5"